### PR TITLE
Missing _compliant init

### PR DESCRIPTION
**Pull request by ymollard**
Should it be initialized to True or False?
Should it come with a version bump to 1.2.4?

### CODE REVIEW

**Comment by nicolas-rabault** [comment]
Yes, it should. But in stepper this value is a duplicata of `self._config[Stepper._MODE_COMPLIANT]` witch is already initialized to true. We should juste only use this one and remove the duplicata.
We found other issues on this example. We will test it and fix it as soon as possible.

We are currently working on a 1.3.0 rev for Pyluos, with big release of all libs.

**Comment by ymollard** [comment]
> We are currently working on a 1.3.0 rev for Pyluos, with big release of all libs.

I've seen that. I'm still using 1.2.3 though because the dev revision has breaking changes, in particular modules are no longer named modules, and that requires re-flashing the gate, Luos 0.7.0... which I couldn't compile so far. I would go for a few fixes on 1.2.3 in parallel of the new revision, which would allow to publish a (first) complete and working release for ROS 2.

**Comment by nicolas-rabault** [comment]
Ok I will create a new 1.2.4 revision with the Steppers updates.

**Comment by nicolas-rabault** [comment]
Revision 1.2.4 is created.

**Pull request closed without merging**
